import { router, json, error } from '@appdeploy/sdk';
import { db } from '@appdeploy/sdk';
import crypto from 'crypto';

type V = number[];
type M = number[][];
const MODEL = { version: 'v4-byte', vocab: 256, dModel: 32, layers: 3, context: 96, ff: 64 };
const B1 = 0.9, B2 = 0.999, EPS = 1e-8;
function rng(seed:number){ let s=seed>>>0; return ()=>{ s=(s*1664525+1013904223)>>>0; return (s/4294967296)-0.5; }; }
function mat(r:number,c:number,seed:number){ const f=rng(seed); return Array.from({length:r},()=>Array.from({length:c},()=>f()*0.08)); }
function zerosLike(a:any):any{ return Array.isArray(a[0])?a.map((r:any)=>r.map(()=>0)):a.map(()=>0); }
function clone(a:any):any{ return Array.isArray(a[0])?a.map((r:any)=>r.slice()):a.slice(); }
function dot(a:V,b:V){ let s=0; for(let i=0;i<a.length;i++) s+=a[i]*b[i]; return s; }
function proj(x:V,w:M){ const y=Array(w[0].length).fill(0); for(let i=0;i<x.length;i++) for(let j=0;j<y.length;j++) y[j]+=x[i]*w[i][j]; return y; }
function add(a:V,b:V){ return a.map((v,i)=>v+b[i]); }
function relu(x:number){ return x>0?x:0; }
function softmax(x:V){ const m=Math.max(...x); const e=x.map(v=>Math.exp(Math.max(-20,Math.min(20,v-m)))); const s=e.reduce((a,b)=>a+b,0)||1; return e.map(v=>v/s); }
function norm(x:V){ const mean=x.reduce((a,b)=>a+b,0)/x.length; const variance=x.reduce((a,v)=>a+(v-mean)*(v-mean),0)/x.length; const inv=1/Math.sqrt(variance+1e-5); return x.map(v=>(v-mean)*inv); }
function baseWeights(){ const w:any={emb:mat(MODEL.vocab,MODEL.dModel,11),pos:mat(MODEL.context,MODEL.dModel,17),blocks:[],out:mat(MODEL.dModel,MODEL.vocab,777),bias:Array(MODEL.vocab).fill(0)}; for(let l=0;l<MODEL.layers;l++) w.blocks.push({q:mat(MODEL.dModel,MODEL.dModel,100+l),k:mat(MODEL.dModel,MODEL.dModel,200+l),v:mat(MODEL.dModel,MODEL.dModel,300+l),o:mat(MODEL.dModel,MODEL.dModel,400+l),ff1:mat(MODEL.dModel,MODEL.ff,500+l),ff2:mat(MODEL.ff,MODEL.dModel,600+l)}); return w; }
const BASE=baseWeights();
function encodeAll(text:string){ return Array.from(Buffer.from(text,'utf8')); }
function encode(text:string){ return encodeAll(text).slice(-MODEL.context); }
interface DatasetRec { name:string; text:string; bytes:number; trainTokens:number; valTokens:number; createdAt:string; }
interface FullState { architecture:string; w:any; m:any; v:any; step:number; trainLoss:number; valLoss:number; samples:number; updatedAt:string; }
function zerosState(w:any):any{ const z:any={emb:zerosLike(w.emb),pos:zerosLike(w.pos),blocks:[],out:zerosLike(w.out),bias:zerosLike(w.bias)}; for(const b of w.blocks) z.blocks.push({q:zerosLike(b.q),k:zerosLike(b.k),v:zerosLike(b.v),o:zerosLike(b.o),ff1:zerosLike(b.ff1),ff2:zerosLike(b.ff2)}); return z; }
function cloneWeights(w:any):any{ const z:any={emb:clone(w.emb),pos:clone(w.pos),blocks:[],out:clone(w.out),bias:clone(w.bias)}; for(const b of w.blocks) z.blocks.push({q:clone(b.q),k:clone(b.k),v:clone(b.v),o:clone(b.o),ff1:clone(b.ff1),ff2:clone(b.ff2)}); return z; }
function newState():FullState{ const w=cloneWeights(BASE); return {architecture:MODEL.version,w,m:zerosState(w),v:zerosState(w),step:0,trainLoss:Math.log(MODEL.vocab),valLoss:Math.log(MODEL.vocab),samples:0,updatedAt:new Date().toISOString()}; }
function compatibleState(r:any){ return r?.architecture===MODEL.version && !!r?.w?.emb && r.w.emb.length===MODEL.vocab && r.w.emb[0]?.length===MODEL.dModel && r.w.pos?.length===MODEL.context && r.w.out?.length===MODEL.dModel && r.w.out[0]?.length===MODEL.vocab && r.w.blocks?.length===MODEL.layers && r.w.blocks[0]?.q?.length===MODEL.dModel; }
async function loadState(){ const {items}=await db.list<FullState>('model_checkpoints',{limit:1}); if(!items[0]||!compatibleState(items[0])) return newState(); const r=items[0]; return {architecture:MODEL.version,w:r.w,m:r.m,v:r.v,step:r.step||0,trainLoss:r.trainLoss||Math.log(MODEL.vocab),valLoss:r.valLoss||Math.log(MODEL.vocab),samples:r.samples||0,updatedAt:r.updatedAt||new Date().toISOString()}; }
async function saveState(s:FullState){ const {items}=await db.list<FullState>('model_checkpoints',{limit:1}); const record={...s,updatedAt:new Date().toISOString()}; if(items[0]) await db.update('model_checkpoints',[{id:items[0].id,record}]); else await db.add('model_checkpoints',[record]); }
class Node { v:number; g:number=0; p:Array<[Node,(g:number)=>number]>; constructor(v:number,p:Array<[Node,(g:number)=>number]> = []){this.v=v;this.p=p;} }
const n=(x:number)=>new Node(x);
const addN=(a:Node,b:Node)=>new Node(a.v+b.v,[[a,g=>g],[b,g=>g]]);
const subN=(a:Node,b:Node)=>new Node(a.v-b.v,[[a,g=>g],[b,g=>-g]]);
const mulN=(a:Node,b:Node)=>new Node(a.v*b.v,[[a,g=>g*b.v],[b,g=>g*a.v]]);
const scaleN=(a:Node,c:number)=>new Node(a.v*c,[[a,g=>g*c]]);
const expN=(a:Node)=>{const e=Math.exp(Math.max(-20,Math.min(20,a.v)));return new Node(e,[[a,g=>g*e]])};
const logN=(a:Node)=>new Node(Math.log(Math.max(a.v,1e-12)),[[a,g=>g/Math.max(a.v,1e-12)]]);
const sqrtN=(a:Node)=>{const s=Math.sqrt(Math.max(a.v,1e-12));return new Node(s,[[a,g=>g/(2*s)]])};
const reluN=(a:Node)=>new Node(relu(a.v),[[a,g=>a.v>0?g:0]]);
function sumN(xs:Node[]){ let r=n(0); for(const x of xs) r=addN(r,x); return r; }
function dotN(a:Node[],b:Node[]){ return sumN(a.map((x,i)=>mulN(x,b[i]))); }
function projN(x:Node[],w:Node[][]){ return Array.from({length:w[0].length},(_,j)=>dotN(x,w.map(r=>r[j]))); }
function divN(a:Node,b:Node){ return new Node(a.v/b.v,[[a,g=>g/b.v],[b,g=>-g*a.v/(b.v*b.v)]]); }
function normN(x:Node[]){ const mean=scaleN(sumN(x),1/x.length); const dif=x.map(v=>subN(v,mean)); const variance=scaleN(sumN(dif.map(v=>mulN(v,v))),1/x.length); const inv=sqrtN(addN(variance,n(1e-5))); return dif.map(v=>divN(v,inv)); }
function backward(loss:Node){ const stack:Node[]=[]; const seen=new Set<Node>(); const walk=(x:Node)=>{if(seen.has(x))return;seen.add(x);for(const [p] of x.p)walk(p);stack.push(x);}; walk(loss); loss.g=1; for(let i=stack.length-1;i>=0;i--){const x=stack[i];for(const [p,f] of x.p)p.g+=f(x.g);} }
function parameterNodes(w:any){ const nodes:any={emb:[],pos:[],blocks:[],out:[],bias:[]}; for(const row of w.emb) nodes.emb.push(row.map(n)); for(const row of w.pos) nodes.pos.push(row.map(n)); for(const b of w.blocks){ const z:any={}; z.q=b.q.map((r:V)=>r.map(n));z.k=b.k.map((r:V)=>r.map(n));z.v=b.v.map((r:V)=>r.map(n));z.o=b.o.map((r:V)=>r.map(n));z.ff1=b.ff1.map((r:V)=>r.map(n));z.ff2=b.ff2.map((r:V)=>r.map(n));nodes.blocks.push(z); } for(const row of w.out) nodes.out.push(row.map(n)); nodes.bias=w.bias.map(n); return nodes; }
function softmaxNodes(xs:Node[]){ const m=Math.max(...xs.map(x=>x.v)); const es=xs.map(x=>expN(subN(x,n(m)))); const den=sumN(es); return es.map(e=>divN(e,den)); }
function transformerFeature(ids:number[],p:any):Node[]{ let x:Node[][]=ids.map((id,i)=>p.emb[id].map((e:Node,d:number)=>addN(e,p.pos[i][d]))); for(const b of p.blocks){ const normed=x.map(normN); const q=normed.map(t=>projN(t,b.q)); const k=normed.map(t=>projN(t,b.k)); const v=normed.map(t=>projN(t,b.v)); x=x.map((old,i)=>{ const scores:Node[]=[]; for(let j=0;j<=i;j++) scores.push(scaleN(dotN(q[i],k[j]),1/Math.sqrt(MODEL.dModel))); const sm=softmaxNodes(scores); const mix=Array(MODEL.dModel).fill(0).map(()=>n(0)); for(let j=0;j<=i;j++) for(let d=0;d<MODEL.dModel;d++) mix[d]=addN(mix[d],mulN(sm[j],v[j][d])); const op=projN(mix,b.o); return old.map((z,d)=>addN(z,op[d])); }); x=x.map(t=>{ const h=projN(normN(t),b.ff1).map(reluN); const op=projN(h,b.ff2); return t.map((z,d)=>addN(z,op[d])); }); } return normN(x[x.length-1]); }
function captureGrads(p:any){ const g:any=zerosState(p); const walk=(a:any,b:any)=>{if(Array.isArray(a[0])) for(let i=0;i<a.length;i++)walk(a[i],b[i]); else for(let i=0;i<a.length;i++)b[i]=a[i].g;}; walk(p.emb,g.emb);walk(p.pos,g.pos);for(let l=0;l<p.blocks.length;l++)for(const key of ['q','k','v','o','ff1','ff2'])walk(p.blocks[l][key],g.blocks[l][key]);walk(p.out,g.out);walk(p.bias,g.bias);return g; }
function applyAdam(a:any,b:any,c:any,g:any,step:number,lr:number,clip:number){if(Array.isArray(a[0]))for(let i=0;i<a.length;i++)applyAdam(a[i],b[i],c[i],g[i],step,lr,clip);else for(let i=0;i<a.length;i++){const gg=Math.max(-clip,Math.min(clip,g[i]));b[i]=B1*b[i]+(1-B1)*gg;c[i]=B2*c[i]+(1-B2)*gg*gg;const mh=b[i]/(1-Math.pow(B1,step));const vh=c[i]/(1-Math.pow(B2,step));a[i]-=lr*mh/(Math.sqrt(vh)+EPS);}}
function adamStep(w:any,m:any,v:any,g:any,step:number,lr:number){let ss=0,count=0;const collect=(x:any)=>{if(Array.isArray(x[0]))for(const r of x)collect(r);else for(const z of x){ss+=z*z;count++;}};collect(g.emb);collect(g.pos);for(const b of g.blocks)for(const k of ['q','k','v','o','ff1','ff2'])collect(b[k]);collect(g.out);collect(g.bias);const clip=Math.max(1,Math.sqrt(ss/Math.max(1,count))*10);applyAdam(w.emb,m.emb,v.emb,g.emb,step,lr,clip);applyAdam(w.pos,m.pos,v.pos,g.pos,step,lr,clip);for(let l=0;l<w.blocks.length;l++)for(const k of ['q','k','v','o','ff1','ff2'])applyAdam(w.blocks[l][k],m.blocks[l][k],v.blocks[l][k],g.blocks[l][k],step,lr,clip);applyAdam(w.out,m.out,v.out,g.out,step,lr,clip);applyAdam(w.bias,m.bias,v.bias,g.bias,step,lr,clip);}
function evalLoss(tokens:number[],state:FullState,start:number,end:number){let loss=0,count=0;const stride=Math.max(1,Math.floor((end-start)/20));for(let pos=Math.max(MODEL.context,start);pos<end;pos+=stride){const ids=tokens.slice(pos-MODEL.context,pos);const p=parameterNodes(state.w);const x=transformerFeature(ids,p);const logits=p.bias.map((b:Node,k:number)=>addN(b,sumN(x.map((v:Node,j:number)=>mulN(v,p.out[j][k])))));const m=Math.max(...logits.map(z=>z.v));const ex=logits.map(z=>Math.exp(z.v-m));const den=ex.reduce((a,b)=>a+b,0)||1;loss-=Math.log(Math.max(ex[tokens[pos]]/den,1e-12));count++;}return count?loss/count:Math.log(MODEL.vocab);}
async function trainModel(text:string,steps:number,lr:number,batchSize:number){const started=Date.now();const clean=text.slice(0,180000);const tokens=encodeAll(clean);if(tokens.length<MODEL.context+2)throw new Error(`Training data must contain at least ${MODEL.context+2} UTF-8 bytes.`);const split=Math.max(MODEL.context+1,Math.floor(tokens.length*.9));const state=await loadState();let total=0;for(let s=0;s<steps;s++){const span=Math.max(1,split-MODEL.context-1);const p=parameterNodes(state.w);let combined:Node|null=null;let batchLoss=0;for(let b=0;b<batchSize;b++){const pos=MODEL.context+Math.floor(Math.random()*span);const ids=tokens.slice(pos-MODEL.context,pos);const target=tokens[pos];const x=transformerFeature(ids,p);const logits=p.bias.map((bias:Node,k:number)=>addN(bias,sumN(x.map((v:Node,j:number)=>mulN(v,p.out[j][k])))));const m=Math.max(...logits.map(z=>z.v));const ex=logits.map(z=>expN(subN(z,n(m))));const den=sumN(ex);const loss=subN(logN(den),logN(ex[target]));batchLoss+=loss.v;combined=combined?addN(combined,loss):loss;}const averaged=scaleN(combined!,1/batchSize);backward(averaged);state.step++;adamStep(state.w,state.m,state.v,captureGrads(p),state.step,lr);total+=batchLoss/batchSize;}state.trainLoss=total/steps;state.valLoss=evalLoss(tokens,state,split,tokens.length-1);state.samples+=steps*batchSize;await saveState(state);return {steps,batchSize,optimizerSteps:steps,trainExamples:steps*batchSize,trainLoss:state.trainLoss,valLoss:state.valLoss,totalSamples:state.samples,elapsedMs:Date.now()-started,tokensPerSecond:Math.round((steps*batchSize)/Math.max((Date.now()-started)/1000,0.001)),checkpoint:'full-parameter-persisted',architecture:MODEL.version,tokenizer:'UTF-8 byte-level tokenizer',vocab:MODEL.vocab,trainTokens:split,valTokens:tokens.length-split,trainedParameters:'embeddings + positional embeddings + attention Q/K/V/O + FFN + output head',optimizer:'Adam with mini-batch averaged gradients and clipping'};}
function numericFeature(ids:number[],w:any):V{let x=ids.map((id,i)=>add(w.emb[id],w.pos[i]));for(const b of w.blocks){const nrm=x.map(norm);const q=nrm.map(t=>proj(t,b.q)),k=nrm.map(t=>proj(t,b.k)),v=nrm.map(t=>proj(t,b.v));x=x.map((old,i)=>{const p=softmax(Array.from({length:i+1},(_,j)=>dot(q[i],k[j])/Math.sqrt(MODEL.dModel)));const mix=Array(MODEL.dModel).fill(0);for(let j=0;j<=i;j++)for(let d=0;d<MODEL.dModel;d++)mix[d]+=p[j]*v[j][d];return add(old,proj(mix,b.o));});x=x.map(t=>{const h=proj(norm(t),b.ff1).map(relu);return add(t,proj(h,b.ff2));});}return norm(x[x.length-1]);}
function logitsNum(x:V,w:any){return w.bias.map((b:number,k:number)=>b+x.reduce((s,v,j)=>s+v*w.out[j][k],0));}
async function generate(prompt:string,maxTokens:number){const state=await loadState();let ids=encode(prompt),outBytes:number[]=[];for(let i=0;i<Math.min(maxTokens,128);i++){const p=softmax(logitsNum(numericFeature(ids,state.w),state.w));let r=Math.random(),best=p.length-1;for(let j=0;j<p.length;j++){r-=p[j];if(r<=0){best=j;break;}}outBytes.push(best);ids=[...ids,best].slice(-MODEL.context);}return Buffer.from(outBytes).toString('utf8');}
interface KeyRec { id:string; name:string; prefix:string; secretHash:string; createdAt:string; requests:number; tokens:number; revoked:boolean; }
function hash(s:string){return crypto.createHash('sha256').update(s).digest('hex');}
async function authenticate(event:any,body:any){const h=event?.headers||{};const auth=h.authorization||h.Authorization||'';const headerSecret=typeof auth==='string'&&auth.startsWith('Bearer ')?auth.slice(7).trim():'';const bodySecret=typeof body?.api_key==='string'?body.api_key.trim():'';const secret=headerSecret||bodySecret;if(!secret)return null;const {items}=await db.list<KeyRec>('api_keys',{limit:100});return items.find(k=>!k.revoked&&k.secretHash===hash(secret))||null;}
export const handler=router({
 'GET /api/health':[async()=>json({ok:true,model:'my-first-transformer-v4-byte',architecture:'decoder-only-transformer',tokenizer:'UTF-8 byte-level',vocab:MODEL.vocab,context:MODEL.context,dModel:MODEL.dModel,layers:MODEL.layers,ff:MODEL.ff,parameters:44288,training:'full-parameter reverse-mode backpropagation with mini-batch Adam'})],
 'GET /api/model':[async()=>{const s=await loadState();const {items}=await db.list<DatasetRec>('training_datasets',{limit:1});const d=items[0];return json({model:'my-first-transformer-v4-byte',version:MODEL.version,architecture:'decoder-only-transformer',tokenizer:'UTF-8 byte-level',vocab:MODEL.vocab,context:MODEL.context,dModel:MODEL.dModel,layers:MODEL.layers,ff:MODEL.ff,trainableParameters:'all Transformer parameters',trainedOptimizerSteps:s.step,trainingExamples:s.samples,trainLoss:s.trainLoss,valLoss:s.valLoss,dataset:d?{name:d.name,bytes:d.bytes,trainTokens:d.trainTokens,valTokens:d.valTokens}:null,updatedAt:s.updatedAt});}],
 'GET /api/datasets':[async()=>{const {items}=await db.list<DatasetRec>('training_datasets',{limit:20});return json(items.map(d=>({id:d.id,name:d.name,bytes:d.bytes,trainTokens:d.trainTokens,valTokens:d.valTokens,createdAt:d.createdAt})));}],
 'POST /api/train':[async({body})=>{const b=(body||{}) as {text?:string;name?:string;steps?:number;learning_rate?:number;batch_size?:number};const text=typeof b.text==='string'?b.text.trim():'';if(!text)return error('training text is required',400);const steps=Math.max(10,Math.min(100,Number(b.steps)||50));const lr=Math.max(.00001,Math.min(.01,Number(b.learning_rate)||.001));const batchSize=Math.max(1,Math.min(8,Number(b.batch_size)||4));try{const result=await trainModel(text,steps,lr,batchSize);const tokens=encodeAll(text.slice(0,180000));const split=Math.max(MODEL.context+1,Math.floor(tokens.length*.9));const name=typeof b.name==='string'&&b.name.trim()?b.name.trim():'Training dataset';const [id]=await db.add('training_datasets',[{name,text:text.slice(0,180000),bytes:tokens.length,trainTokens:split,valTokens:Math.max(0,tokens.length-split),createdAt:new Date().toISOString()}]);return json({...result,datasetId:id,datasetName:name});}catch(e){return error(e instanceof Error?e.message:'training failed',400);}}],
 'POST /api/keys':[async({body})=>{const b=(body||{}) as {name?:string};const raw='mfa_'+crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,'');const [id]=await db.add('api_keys',[{name:b.name?.trim()||'Default key',prefix:raw.slice(0,12),secretHash:hash(raw),createdAt:new Date().toISOString(),requests:0,tokens:0,revoked:false}]);if(!id)return error('Could not create API key',500);return json({id,key:raw,warning:'Copy this key now. It is only returned at creation.'});}],
 'GET /api/keys':[async()=>{const {items}=await db.list<KeyRec>('api_keys',{limit:100});return json(items.map(k=>({id:k.id,name:k.name,prefix:k.prefix,createdAt:k.createdAt,requests:k.requests,tokens:k.tokens,revoked:k.revoked})));}],
 'POST /api/keys/:id/revoke':[async({params})=>{const [k]=await db.get<KeyRec>('api_keys',[params.id]);if(!k)return error('API key not found',404);const ok=await db.update('api_keys',[{id:k.id,record:{...k,revoked:true}}]);return ok[0]?json({revoked:true}):error('Could not revoke API key',500);}],
 'POST /api/model/generate':[async({body})=>{const b=(body||{}) as {prompt?:string;max_tokens?:number};const prompt=typeof b.prompt==='string'?b.prompt:'';if(!prompt)return error('prompt is required',400);const maxTokens=Math.max(1,Math.min(64,Number(b.max_tokens)||32));const text=await generate(prompt,maxTokens);return json({id:'gen_'+crypto.randomUUID(),model:MODEL.version,choices:[{text,finish_reason:'length'}],usage:{prompt_tokens:encode(prompt).length,completion_tokens:text.length,total_tokens:encode(prompt).length+text.length}});}],
 'POST /api/v1/generate':[async(ctx)=>{const key=await authenticate(ctx.event,ctx.body);if(!key)return error('Missing or invalid API key. Create a key and send it as Bearer <key> or api_key in the request body.',401);const b=(ctx.body||{}) as {prompt?:string;max_tokens?:number};const prompt=typeof b.prompt==='string'?b.prompt:'';if(!prompt)return error('prompt is required',400);const maxTokens=Math.max(1,Math.min(64,Number(b.max_tokens)||32));const text=await generate(prompt,maxTokens);const tokenCount=encode(prompt).length+text.length;await db.update('api_keys',[{id:key.id,record:{...key,requests:key.requests+1,tokens:key.tokens+tokenCount}}]);return json({id:'gen_'+crypto.randomUUID(),model:MODEL.version,choices:[{text,finish_reason:'length'}],usage:{prompt_tokens:encode(prompt).length,completion_tokens:text.length,total_tokens:tokenCount}}); }]
});
